### ISSUE TITLE
Incorrect Conjugation

### ISSUE THREAD

**Issue by rmeier-yerkes** [SekouDiaoNlp/mlconjug3#89] opened 2020-10-05 00:10 UTC
* MLConjug version: 3.7.11
* Python version: 3.7.4
* Operating System: Lubuntu v16.4

If I run this code:
default_conjugator = mlconjug3.Conjugator(language='en')
print(default_conjugator.conjugate('swing').conjug_info['indicative']['indicative present']['3s']

Python outputs this:
clings

Not swings, but clings.

**Comment by SekouDiaoNlp** [comment] 2020-10-05 00:56
Hi @rmeier-yerkes ,

Thank you for submitting this issue .
I will investigate the cause of the issue and release a new version of mlconjug3 as soon as possible (possibly today).

Thans again for using mlconjug3.

Peace,

SekouDiaoNlp

**Comment by SekouDiaoNlp** [comment] 2020-10-14 10:02
Hi @rmeier-yerkes .

I Just merged the fix to your issue and released the newest version mlconjug3 v3.7.13 on PyPi.

You just have to type `pip install mlconjug3` in your terminal.

Thanks again for submitting this bug issue.

Peace, Love and have fun.

SekouDiaoNlp

**Closed** 2020-10-14 14:09 UTC
Labels: bug, good first issue
