### ISSUE TITLE
ModuleNotFoundError: No module named 'mlconjug.mlconjug3'

### ISSUE THREAD

**Issue by VoxLight** [SekouDiaoNlp/mlconjug3#2] opened 2020-02-27 17:43 UTC
**Describe the bug**
I am getting the error "ModuleNotFoundError: No module named 'mlconjug.mlconjug3'"
after installing this package with pip and trying to import it.

**To Reproduce**
1. Install mlconjug3 with `py -3.8 -m pip install mlconjug3`
2. Import mlconjug3 with `import mlconjug`
3. Run the script

**Expected behavior**
For the module to import succesfully with no error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
- Python 3.8

**Additional context**
 The original mlconjug, not mlconjug3, works perfectly fine (it's what I have been using). Once I learned that there was an updated mlconjug3 module, i wanted to get it since it was shown to be made specifically to work with python 3 (verses mlconjug being made for python 2). It's suprising that the old mlconjug works.

**Comment by SekouDiaoNlp** [comment] 2020-03-04 18:05
Hi @VoxLight , I will investigate this issue and try to fix it and get back to you by Saturday. Thanks for using mlconjug.

**Comment by SekouDiaoNlp** [comment] 2020-03-10 08:00
Hi @VoxLight , I investigated the issue this weekend and it appears I did not update the documentation.

You should use import mlconjug3 instead of import mlconjug.

This should fix this issue. I will update the documentation in the next few days.

Cheers,

SekouDiaoNlp.

**Comment by Jmorr10** [comment] 2020-03-11 02:15
@SekouDiaoNlp 

Unfortunately, that doesn't work either. I get: "ModuleNotFoundError: No module named 'mlconjug3'"

I am able to import the dependencies, it's not a path issue. I suspect there's a problem with the package name. In my site-packages folder, it is installed under mlconjug (not mlconjug3),

**Comment by SekouDiaoNlp** [comment] 2020-03-12 16:33
Hi @VoxLight . I couldn't reproduce your issue.

I am glad you found a workaround.

I will investigate further and let you know the results of my investigations.

Cheers,
SekouDiaoNlp.

**Comment by halimess** [comment] 2020-03-30 07:18
I have the same issue.

#### To Reproduce
1. `python3 -m venv venv`
2. `source venv/bin/activate`
3. `pip install mlconjug3`
4. `import mlconjug3`

#### Desktop
* macOS
* python 3.7

**Comment by SekouDiaoNlp** [comment] 2020-03-31 09:28
Hi @halimess @VoxLight and @Jmorr10 , I am currently on holidays, and don't have access to my development environment. I found the cause of the issue and will release a new version by next week.

I will keep you informed as soon as mlconjug3 version  3.7.2 is released.

Cheers, and keep safe with the coronavirus going around.

SekouDiaoNlp

**Comment by SekouDiaoNlp** [comment] 2020-04-30 00:02
Hi @Jmorr10 , @halimess and @VoxLight !

I hope you all are well with the pendemic.

Due to the coronavirus lockdown I was unable to access my development environment for a few weeks, but now I have access to it since today :)

I fixed the code for this issue and updated the dependencies of the project.
I just pushed the fix to the master branch and you can pull the new version directly from github.

I will publish v 3.7.2 tomorrow on PyPi.

Thanks for using mlconjug and sorry for the delay for pushing the fix.

Peace and Stay safe.

**Comment by SekouDiaoNlp** [comment] 2020-04-30 11:26
Hi @Jmorr10 , @halimess and @VoxLight .

I just released version 3.7.3 of mlconjug3.

This version fixes this issue and the module should install correctly and the imports should work as expected.

Can you check the new version and let me know if you still have the issue?

Thanks in advance, and thank you again for submitting the issue.

Cheers,

SekouDiaoNlp.

**Closed** 2020-05-17 20:45 UTC
Labels: bug
